function out = expmapSO3(axis,theta)     
% Return the 3x3 exponential map of an angle (essentially a rotation
% matrix)
% axis: unit direction vector denoting joints axis of rotation
% theta: symbolic variabile denoting angle rotation of joint
            w1 = axis(1,1);
            w2 = axis(2,1);
            w3 = axis(3,1);
            c = cos(theta);
            s = sin(theta);
            v = 1 - cos(theta);  
            out = [(((w1^2)*v)+c)...
                (w1*w2*v)-(w3*s)...
                (w1*w3*v)+(w2*s);...
                (w1*w2*v)+(w3*s)...
                ((w2^2)*v)+c...
                (w2*w3*v)-(w1*s);...
                (w1*w3*v)-(w2*s)...
                (w2*w3*v)+(w1*s)...
                ((w3^2)*v)+c];
end

